const STORAGE_KEY="crm-aparcament-rector-v1";
const statuses=["Pendent de contactar","Contactat","Interessat","No ha contestat","No interessat","Reserva feta","Contracte signat"];
const state={clients:[],units:[],selectedId:null,filters:{search:"",interest:"",nextStep:""}};
const $=s=>document.querySelector(s);
const els={board:$("#board"),stats:$("#stats"),clientFile:$("#clientFile"),unitFile:$("#unitFile"),exportClients:$("#exportClients"),searchInput:$("#searchInput"),interestFilter:$("#interestFilter"),nextStepFilter:$("#nextStepFilter"),quickAddForm:$("#quickAddForm"),quickName:$("#quickName"),quickPhone:$("#quickPhone"),quickEmail:$("#quickEmail"),quickInterest:$("#quickInterest"),resetDemo:$("#resetDemo"),dialog:$("#clientDialog"),dialogTitle:$("#dialogTitle"),clientName:$("#clientName"),clientPhone:$("#clientPhone"),clientEmail:$("#clientEmail"),clientInterest:$("#clientInterest"),clientStatus:$("#clientStatus"),clientPriority:$("#clientPriority"),assignedUnit:$("#assignedUnit"),unitList:$("#unitList"),lastContact:$("#lastContact"),nextStep:$("#nextStep"),notes:$("#notes"),saveClient:$("#saveClient"),deleteClient:$("#deleteClient")};
function normalizeKey(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"")}
function pick(row,aliases){const entries=Object.entries(row),keys=aliases.map(normalizeKey),found=entries.find(([k])=>keys.includes(normalizeKey(k)));return found?String(found[1]??"").trim():""}
function compactRow(row){return row.map(v=>String(v??"").trim())}
function rowToObject(headers,row){return headers.reduce((o,h,i)=>(o[h||`Columna ${i+1}`]=row[i]??"",o),{})}
function headerScore(row,aliases){const cells=compactRow(row).map(normalizeKey);return aliases.reduce((score,group)=>score+(cells.some(c=>group.map(normalizeKey).includes(c))?1:0),0)}
function rowsFromHeader(rawRows,aliases,fallbackHeaders){const rows=rawRows.map(compactRow).filter(r=>r.some(Boolean));const best=rows.map((row,index)=>({index,score:headerScore(row,aliases)})).reduce((a,b)=>b.score>a.score?b:a,{index:-1,score:0});if(best.score>0){const headers=rows[best.index];return rows.slice(best.index+1).map(row=>rowToObject(headers,row))}const first=rows.findIndex(row=>row.filter(Boolean).length>1);return (first>=0?rows.slice(first):rows).map(row=>rowToObject(fallbackHeaders,row))}
function uuid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
function todayIso(){return new Date().toISOString().slice(0,10)}
function normalizeInterest(value){const text=String(value||"").toLowerCase(),normalized=normalizeKey(value);if(text.includes("caravana")||text.includes("autocaravana"))return"caravana";if(text.includes("traster")&&(normalized.includes("plac")||text.includes("parking")||text.includes("aparc")))return"placa + traster";if(text.includes("traster"))return"traster";if(normalized.includes("plac")||text.includes("parking")||text.includes("aparc"))return"placa normal";return value?"altres":"placa normal"}
function titleCaseInterest(value){return({"placa normal":"Placa normal",caravana:"Caravana",traster:"Traster","placa + traster":"Placa + traster",altres:"Altres"})[normalizeInterest(value)]||"Altres"}
function normalizeStatus(value){const key=normalizeKey(value);return({"":"Pendent de contactar",nou:"Pendent de contactar",contactar:"Pendent de contactar",pendentdecontactar:"Pendent de contactar",esperantresposta:"Contactat",contactat:"Contactat",interessat:"Interessat",reservaenviada:"Reserva feta",reservat:"Reserva feta",reservafeta:"Reserva feta",contractat:"Contracte signat",contractesignat:"Contracte signat",nointeressat:"No interessat",nohacontestat:"No ha contestat"})[key]||"Pendent de contactar"}
function makeClient(data){return{id:uuid(),name:data.name||"Sense nom",phone:data.phone||"",email:data.email||"",interest:titleCaseInterest(data.interest),status:normalizeStatus(data.status),priority:data.priority||"Normal",assignedUnit:data.assignedUnit||"",lastContact:data.lastContact||"",nextStep:data.nextStep||"Contactar",notes:data.notes||"",createdAt:data.createdAt||todayIso()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({clients:state.clients,units:state.units}))}
function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");state.clients=Array.isArray(parsed.clients)?parsed.clients.map(c=>({...c,status:normalizeStatus(c.status)})):[];state.units=Array.isArray(parsed.units)?parsed.units:[];save()}catch{state.clients=[];state.units=[]}}
function escapeHtml(value){return String(value||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function filteredClients(){return state.clients.filter(c=>{const haystack=[c.name,c.phone,c.email,c.interest,c.assignedUnit,c.notes].join(" ").toLowerCase();return(!state.filters.search||haystack.includes(state.filters.search.toLowerCase()))&&(!state.filters.interest||normalizeInterest(c.interest)===state.filters.interest)&&(!state.filters.nextStep||normalizeKey(c.nextStep)===normalizeKey(state.filters.nextStep))})}
function renderStats(){els.stats.innerHTML=statuses.map(status=>`<div class="stat"><strong>${state.clients.filter(c=>c.status===status).length}</strong><span>${escapeHtml(status)}</span></div>`).join("")}
function renderUnitList(){els.unitList.innerHTML=state.units.map(u=>`<option value="${escapeHtml(u.label)}">${escapeHtml(u.detail)}</option>`).join("")}
function renderCard(c){const contact=[c.phone,c.email].filter(Boolean).join(" - "),assigned=c.assignedUnit?`<span class="pill warn">${escapeHtml(c.assignedUnit)}</span>`:"",next=c.nextStep?`<span class="pill">${escapeHtml(c.nextStep)}</span>`:"";return`<button class="card" type="button" data-id="${escapeHtml(c.id)}"><span class="card-title"><span>${escapeHtml(c.name)}</span><span>${escapeHtml(c.priority)}</span></span><span class="card-meta">${escapeHtml(contact||"Sense contacte")}</span><span class="card-meta">${escapeHtml(c.interest)}</span><span class="pill-row">${next}${assigned}</span></button>`}
function renderBoard(){const clients=filteredClients();els.board.innerHTML=statuses.map(status=>{const columnClients=clients.filter(c=>c.status===status);return`<section class="column"><div class="column-header"><h3>${escapeHtml(status)}</h3><span class="count">${columnClients.length}</span></div>${columnClients.length?columnClients.map(renderCard).join(""):`<div class="empty">Cap client</div>`}</section>`}).join("");document.querySelectorAll(".card").forEach(card=>card.addEventListener("click",()=>openClient(card.dataset.id)))}
function render(){renderStats();renderUnitList();renderBoard()}
async function readWorkbook(file){if(!window.XLSX){alert("La llibreria d'Excel encara s'esta carregant. Torna-ho a provar en uns segons.");return[]}const buffer=await file.arrayBuffer(),workbook=XLSX.read(buffer,{type:"array"}),sheet=workbook.Sheets[workbook.SheetNames[0]];return XLSX.utils.sheet_to_json(sheet,{header:1,defval:""})}
async function importClients(file){const rawRows=await readWorkbook(file);const rows=rowsFromHeader(rawRows,[["nom","nombre","nom/cognoms","nom cognoms","nom i cognoms","nom complet","client","persona","interessat"],["telefon","telefono","tel","mobile","mobil","whatsapp"],["email","mail","correu","correo","correu electronic","e-mail"],["interes","interessat","tipus","tipus interes","busca","necessitat","placa","comentaris"]],["Nom","Telefon","Email","Interes","Comentaris"]);const clients=rows.map(row=>{const notes=pick(row,["comentaris","observacions","notes","comentario","columna 4","columna 5"]);const interest=pick(row,["interes","interessat","tipus","tipus interes","busca","necessitat","placa","Interes","columna 4"])||notes;return makeClient({name:pick(row,["nom","nombre","nom/cognoms","nom cognoms","nom i cognoms","nom complet","client","persona","interessat","Nom"]),phone:pick(row,["telefon","telefono","tel","mobile","mobil","whatsapp","Telefon"]),email:pick(row,["email","mail","correu","correo","correu electronic","e-mail","Email"]),interest,notes})}).filter(c=>!(["nom","nomcognoms","nomcognom"].includes(normalizeKey(c.name)))&&(c.name!=="Sense nom"||c.phone||c.email||c.notes));const existing=new Set(state.clients.map(c=>`${normalizeKey(c.name)}-${normalizeKey(c.phone)}`));const newClients=clients.filter(c=>{const key=`${normalizeKey(c.name)}-${normalizeKey(c.phone)}`;if(existing.has(key))return false;existing.add(key);return true});state.clients=[...state.clients,...newClients];save();render();alert(newClients.length?`Importats ${newClients.length} clients nous.`:"No he trobat clients nous. Revisa que has triat l'Excel de clients i no el de places/trasters.")}
async function importUnits(file){const rawRows=await readWorkbook(file);const rows=rowsFromHeader(rawRows,[["numero","num","n","placa","n placa","numero placa","traster"],["planta","nivell","floor","pl"],["tipus","tipologia","classe","descripcio","tipo"]],["Numero","Tipo","Planta","m2","Preu","Estat"]);state.units=rows.map(row=>{const number=pick(row,["numero","num","n","placa","n placa","numero placa","traster"]),floor=pick(row,["planta","nivell","floor","pl"]),type=pick(row,["tipus","tipologia","classe","descripcio","tipo"]),label=[number,floor?`planta ${floor}`:"",type].filter(Boolean).join(" - ");return{id:uuid(),label:number||label||"Unitat",detail:label||number||"Unitat",raw:row}}).filter(u=>u.label);save();render();alert(`Importades ${state.units.length} unitats per assignar.`)}
function openClient(id){const c=state.clients.find(item=>item.id===id);if(!c)return;state.selectedId=id;els.dialogTitle.textContent=c.name;els.clientName.value=c.name;els.clientPhone.value=c.phone;els.clientEmail.value=c.email;els.clientInterest.value=c.interest;els.clientStatus.value=c.status;els.clientPriority.value=c.priority;els.assignedUnit.value=c.assignedUnit;els.lastContact.value=c.lastContact;els.nextStep.value=c.nextStep;els.notes.value=c.notes;els.dialog.showModal()}
function saveSelectedClient(){const c=state.clients.find(item=>item.id===state.selectedId);if(!c)return;c.name=els.clientName.value.trim()||"Sense nom";c.phone=els.clientPhone.value.trim();c.email=els.clientEmail.value.trim();c.interest=els.clientInterest.value;c.status=els.clientStatus.value;c.priority=els.clientPriority.value;c.assignedUnit=els.assignedUnit.value.trim();c.lastContact=els.lastContact.value;c.nextStep=els.nextStep.value;c.notes=els.notes.value.trim();save();render();els.dialog.close()}
function deleteSelectedClient(){if(!state.selectedId)return;const c=state.clients.find(item=>item.id===state.selectedId);if(!c||!confirm(`Eliminar ${c.name}?`))return;state.clients=state.clients.filter(item=>item.id!==state.selectedId);state.selectedId=null;save();render();els.dialog.close()}
function exportClients(){if(!window.XLSX){alert("La llibreria d'Excel encara s'esta carregant. Torna-ho a provar en uns segons.");return}const rows=state.clients.map(c=>({Nom:c.name,Telefon:c.phone,Email:c.email,Interes:c.interest,Estat:c.status,Prioritat:c.priority,"Placa o traster assignat":c.assignedUnit,"Ultim contacte":c.lastContact,"Proper pas":c.nextStep,Comentaris:c.notes}));const sheet=XLSX.utils.json_to_sheet(rows),workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,sheet,"Clients");XLSX.writeFile(workbook,"crm-aparcament-rector-clients.xlsx")}
function bindEvents(){statuses.forEach(status=>{const option=document.createElement("option");option.textContent=status;els.clientStatus.appendChild(option)});els.clientFile.addEventListener("change",e=>{const file=e.target.files?.[0];if(file)importClients(file);e.target.value=""});els.unitFile.addEventListener("change",e=>{const file=e.target.files?.[0];if(file)importUnits(file);e.target.value=""});els.exportClients.addEventListener("click",exportClients);els.searchInput.addEventListener("input",()=>{state.filters.search=els.searchInput.value;renderBoard()});els.interestFilter.addEventListener("change",()=>{state.filters.interest=els.interestFilter.value;renderBoard()});els.nextStepFilter.addEventListener("change",()=>{state.filters.nextStep=els.nextStepFilter.value;renderBoard()});els.quickAddForm.addEventListener("submit",e=>{e.preventDefault();state.clients.unshift(makeClient({name:els.quickName.value.trim(),phone:els.quickPhone.value.trim(),email:els.quickEmail.value.trim(),interest:els.quickInterest.value}));els.quickAddForm.reset();save();render()});els.saveClient.addEventListener("click",saveSelectedClient);els.deleteClient.addEventListener("click",deleteSelectedClient);els.resetDemo.addEventListener("click",()=>{if(!confirm("Vols netejar totes les dades guardades en aquest navegador?"))return;state.clients=[];state.units=[];save();render()})}
load();bindEvents();render();window.scrollTo({left:0,top:0});
